# Maps every occasion category → subcategories → mood → Unsplash search keyword

CATEGORIES: dict[str, dict] = {
    "Faith & Spiritual": {
        "subcategories": [
            "Christian encouragement",
            "Bible verse inspired",
            "Prayer & hope",
            "General spiritual",
            "Gratitude & blessings",
            "Islamic peace",
            "Jewish wisdom",
            "Baptism & confirmation",
            "First communion",
            "Easter faith",
            "Christmas nativity",
        ],
        "mood": "uplifting",
        "unsplash_keyword": "golden light sunrise cross church",
    },
    "Healing & Wellness": {
        "subcategories": [
            "Mental health & anxiety",
            "Progress not perfection",
            "One day at a time",
            "Grief & loss",
            "Self-love",
            "Sobriety & recovery",
            "Body positivity",
            "Trust the process",
            "Choose joy",
            "You can do hard things",
        ],
        "mood": "calm",
        "unsplash_keyword": "soft nature morning mist gentle",
    },
    "Love & Relationships": {
        "subcategories": [
            "Anniversary",
            "Wedding & newlywed",
            "Friendship",
            "Motherhood",
            "Fatherhood",
            "Grandmother",
            "Grandfather",
            "Daughter",
            "Son",
            "Sister",
            "Brother",
            "Best friend",
            "Family bonds",
        ],
        "mood": "warm",
        "unsplash_keyword": "soft bokeh flowers warm sunset",
    },
    "Life Events": {
        "subcategories": [
            "Graduation",
            "New job & promotion",
            "Retirement",
            "New home & housewarming",
            "Wedding",
            "Baby shower",
            "New parents",
            "Birthday",
            "New beginnings",
        ],
        "mood": "joyful",
        "unsplash_keyword": "confetti celebration balloons golden light",
    },
    "Motivation & Mindset": {
        "subcategories": [
            "Entrepreneur & hustle",
            "Growth mindset",
            "Morning routine",
            "Resilience",
            "Keep going",
            "Dream big",
            "Leadership",
            "Discipline & focus",
        ],
        "mood": "powerful",
        "unsplash_keyword": "mountain peak sunrise dramatic epic",
    },
    "Professional Niches": {
        "subcategories": [
            "Nurse & healthcare",
            "Doctor",
            "Dental hygienist",
            "Teacher",
            "Engineer",
            "Police officer",
            "Firefighter",
            "Military",
            "Veterinarian",
        ],
        "mood": "proud",
        "unsplash_keyword": "professional clean light purpose",
    },
    "Fitness & Sports": {
        "subcategories": [
            "Gym & bodybuilding",
            "Running",
            "Yoga",
            "Volleyball",
            "General fitness",
            "Discipline beats motivation",
            "Train with purpose",
        ],
        "mood": "energetic",
        "unsplash_keyword": "athlete training sunrise motion strong",
    },
    "Holidays & Seasonal": {
        "subcategories": [
            "New Year",
            "Valentine's Day",
            "St. Patrick's Day",
            "Easter",
            "Mother's Day",
            "Father's Day",
            "Memorial Day",
            "Independence Day",
            "Labor Day",
            "Halloween",
            "Thanksgiving",
            "Christmas",
            "Hanukkah",
            "New Year's Eve",
        ],
        "mood": "festive",
        "unsplash_keyword": "holiday seasonal cozy warm light",
    },
    "Seasonal Collections": {
        "subcategories": [
            "Spring growth",
            "Summer memories",
            "Autumn gratitude",
            "Winter peace",
        ],
        "mood": "serene",
        "unsplash_keyword": "seasonal nature landscape beautiful",
    },
    "Civic & Political": {
        "subcategories": [
            "Patriotism & freedom",
            "Voting & democracy",
            "Military & veteran honor",
            "First responders",
            "Community & unity",
        ],
        "mood": "bold",
        "unsplash_keyword": "american flag landscape blue sky",
    },
    "Nature & Scenic": {
        "subcategories": [
            "Mountain serenity",
            "Beach & ocean waves",
            "Forest stillness",
            "Sunrise & sunset",
            "Starry night",
            "Waterfall wonder",
            "Wildflowers",
            "Desert landscape",
            "Northern lights",
            "Tropical island",
            "Country roads",
            "Lake reflection",
        ],
        "mood": "serene",
        "unsplash_keyword": "scenic nature landscape peaceful beautiful",
    },
    "Room Decor": {
        "subcategories": [
            "Office",
            "Home office",
            "Dorm room",
            "Bedroom",
            "Nursery",
            "Living room",
            "Classroom",
            "Gym room",
        ],
        "mood": "calm",
        "unsplash_keyword": "minimal clean interior cozy light",
    },
    "Office & Business": {
        "subcategories": [
            "Teamwork",
            "Innovation",
            "Success mindset",
            "Work-life balance",
            "Leadership",
            "Corporate motivation",
        ],
        "mood": "professional",
        "unsplash_keyword": "clean minimal desk modern light",
    },
    "Dental School & Healthcare": {
        "subcategories": [
            "DAT motivation",
            "Dental school journey",
            "Future DDS",
            "White coat ceremony",
            "Anatomy study room",
            "Boards & exams",
            "Practice owner dream",
            "Dental hygienist",
            "Pre-dental motivation",
        ],
        "mood": "proud",
        "unsplash_keyword": "medical professional clean white light purpose",
    },
    "Future Professions": {
        "subcategories": [
            "Future dentist",
            "Future doctor",
            "Future nurse",
            "Future teacher",
            "Future engineer",
            "Future lawyer",
            "Future veterinarian",
            "Future entrepreneur",
        ],
        "mood": "powerful",
        "unsplash_keyword": "sunrise ambitious vision future light",
    },
    "Children's Confidence": {
        "subcategories": [
            "Brave little dreamer",
            "You can learn anything",
            "Kindness matters",
            "Be yourself",
            "You are enough",
            "Nursery affirmations",
            "Classroom courage",
        ],
        "mood": "joyful",
        "unsplash_keyword": "soft colorful gentle children bright",
    },
    "Recovery & Healing Journey": {
        "subcategories": [
            "Divorce & new chapter",
            "Grief & loss",
            "Addiction recovery",
            "Cancer recovery",
            "Healing is not linear",
            "Starting over",
            "Survivor strength",
        ],
        "mood": "calm",
        "unsplash_keyword": "soft sunrise hope gentle light new day",
    },
    "Personalized — Life Chapters": {
        "subcategories": [
            "Graduation chapter",
            "New career chapter",
            "Recovery chapter",
            "Fitness goal chapter",
            "New parent chapter",
            "Retirement chapter",
        ],
        "mood": "powerful",
        "unsplash_keyword": "open road journey sunrise path forward",
    },
    "Personalized — Family Legacy": {
        "subcategories": [
            "Family name & values",
            "Housewarming gift",
            "Wedding gift",
            "Multi-generation tribute",
        ],
        "mood": "warm",
        "unsplash_keyword": "warm home family light cozy",
    },
    "Christian Prayers by Situation": {
        "subcategories": [
            "Anxiety prayer",
            "Student exam prayer",
            "Dental school prayer",
            "New mother prayer",
            "Cancer recovery prayer",
            "Marriage prayer",
            "Grief prayer",
            "New job prayer",
            "Financial peace prayer",
        ],
        "mood": "uplifting",
        "unsplash_keyword": "golden light soft prayer hope peace",
    },
}

MOOD_TO_UNSPLASH: dict[str, str] = {
    "uplifting": "golden light sunrise hope sky",
    "calm": "soft morning mist nature gentle",
    "warm": "soft bokeh flowers warm light",
    "joyful": "bright colorful celebration joy balloons",
    "powerful": "dramatic mountain peak storm epic",
    "proud": "purpose achievement light clean",
    "energetic": "motion athlete sunrise training",
    "festive": "holiday seasonal cozy warm light",
    "bold": "strong landscape flag sky dramatic",
    "serene": "peaceful lake forest misty calm",
    "professional": "clean minimal modern light",
}


def get_mood(category: str, subcategory: str) -> str:
    """Return the mood string for a given category."""
    return CATEGORIES.get(category, {}).get("mood", "serene")


def get_unsplash_keyword(mood: str) -> str:
    """Return Unsplash search keyword for a given mood."""
    return MOOD_TO_UNSPLASH.get(mood, "scenic nature landscape")
