import random

QUOTE_LIBRARY: dict[str, list[str]] = {
    "Faith & Spiritual": [
        "Let your faith be bigger than your fear.",
        "In every storm, peace waits in the shelter of prayer.",
        "Grace is not earned — it is freely given.",
        "Where hope grows, miracles blossom.",
        "Walk by faith, not by what you can see.",
        "Every sunrise is a reminder that grace is new.",
        "God's timing is always perfect.",
        "Let go and let grace guide you.",
        "The light within you is stronger than any darkness around you.",
        "Prayer is not asking — it is listening.",
        "Trust the journey even when you cannot see the road.",
        "Blessed are those who believe before they see.",
    ],
    "Healing & Wellness": [
        "Healing is not linear — every step forward counts.",
        "You are allowed to take up space in this world.",
        "Rest is not giving up — it is gathering strength.",
        "Your feelings are valid. Your recovery is real.",
        "Be patient with yourself — growth takes time.",
        "You survived every hard day so far. Today is no different.",
        "Peace is not the absence of pain. It is choosing yourself anyway.",
        "Every breath is a new beginning.",
        "You are worthy of kindness, especially from yourself.",
        "Healing happens slowly, then all at once.",
    ],
    "Love & Relationships": [
        "Love is not a destination — it is the journey taken together.",
        "In your arms, I found my home.",
        "The best thing to hold onto in life is each other.",
        "A great love is not found — it is built, day by day.",
        "Still my favorite person after all this time.",
        "Together is the best place to be.",
        "Love grows best in small houses and big hearts.",
        "You are my today and all of my tomorrows.",
        "A mother's love is the compass that guides us home.",
        "A father's love is the quiet strength that shapes a child's world.",
        "Family: where life begins and love never ends.",
        "True friendship doubles joy and divides grief.",
    ],
    "Milestone Celebrations": [
        "Today is just the beginning of your greatest chapter.",
        "Look how far you have come — and look how far you will go.",
        "Celebrate every step — even the small ones lead somewhere great.",
        "A new beginning is the bravest kind of chapter.",
        "You did not come this far only to come this far.",
        "Graduates: you did not just earn a degree — you earned your story.",
        "Retirement: not the end of work, but the beginning of freedom.",
        "The world just got a little brighter — welcome, little one.",
        "New home, new memories, new story.",
        "Promoted: because excellence speaks for itself.",
    ],
    "Motivation & Mindset": [
        "The difference between ordinary and extraordinary is that little extra.",
        "Start before you are ready. Grow as you go.",
        "Discipline is choosing what you want most over what you want now.",
        "Success is not given. It is built one decision at a time.",
        "Your only competition is who you were yesterday.",
        "Dream big. Work hard. Stay humble.",
        "The grind is silent. The results are loud.",
        "Every expert was once a beginner who refused to quit.",
        "Create the life you cannot stop thinking about.",
        "Hard work beats talent when talent does not work hard.",
        "Great leaders do not create followers — they create more leaders.",
        "Innovation begins where comfort ends.",
    ],
    "Holidays & Seasonal": [
        "May your Christmas be wrapped in peace and tied with love.",
        "He is risen — and because of that, everything is different.",
        "Grateful hearts make grateful homes — Happy Thanksgiving.",
        "Love is not just for Valentine's Day — it is for every single day.",
        "To the woman who made home feel like heaven — Happy Mother's Day.",
        "Behind every great child is a dad who believed first.",
        "Land of the free because of the brave.",
        "New year, same soul — but a braver, wiser version.",
        "Fall: the art of letting go beautifully.",
        "Winter is not the end — it is the earth resting before it blooms.",
        "Spring: proof that after every winter, life begins again.",
        "Summer is the season when memories are made and kept forever.",
    ],
    "Civic & Political": [
        "Freedom is not free — it is purchased with courage and sacrifice.",
        "Democracy is not a spectator sport. Vote.",
        "We do not inherit the earth from our ancestors — we borrow it from our children.",
        "Honor the fallen by living with purpose.",
        "Service to others is the rent we pay for our place on earth.",
        "In unity there is strength. In strength there is freedom.",
        "The firefighter runs toward the fire so you do not have to.",
        "A nation's character is measured by how it treats its most vulnerable.",
        "Your voice matters. Your vote matters. Show up.",
        "Heroes are ordinary people who make extraordinary choices.",
    ],
    "Nature & Peace": [
        "The mountains are calling and I must go.",
        "Not all who wander are lost — some are just finding themselves.",
        "In the waves of change, I found my direction.",
        "The forest is the original cathedral.",
        "Be still and let the morning remind you — today is a gift.",
        "Every sunset carries the seeds of tomorrow's sunrise.",
        "The ocean does not apologize for its depth. Neither should you.",
        "Peace begins where ambition ends and wonder begins.",
        "Stars remind us that even in darkness, light exists.",
        "Slow down. The earth has been here longer than your hurry.",
    ],
    "Office & Business": [
        "Great teams do not happen by accident — they are built with intention.",
        "Do what you love and you will never work a day in your life.",
        "Success is a team sport. Nobody wins alone.",
        "Ideas without action are just dreams. Act.",
        "Work hard in silence. Let success make the noise.",
        "Balance is not something you find — it is something you build.",
        "Create. Innovate. Lead.",
        "Your work is a reflection of your standards. Set them high.",
    ],
}


def get_quotes(category: str, count: int = 5) -> list[str]:
    """Return `count` unique random quotes from the given category."""
    pool = QUOTE_LIBRARY.get(category, [])
    if not pool:
        return []
    return random.sample(pool, min(count, len(pool)))
