"""100+ SEO-optimized Etsy listing templates by niche."""
from dataclasses import dataclass


@dataclass
class ListingTemplate:
    """One ready-made Etsy listing: title, 13 tags, hook, price tier, product."""
    niche: str
    title: str          # <=140 chars, keyword-rich
    tags: list[str]     # exactly 13 tags, each <=20 chars
    description_hook: str  # 2-sentence listing opener
    price_tier: str     # "budget"/$14-19, "mid"/$24-35, "premium"/$45-65
    product_type: str   # "poster", "canvas", "framed", "digital"


SEO_TEMPLATES: list[ListingTemplate] = [

    # ── DAUGHTER GIFTS (8 templates) ──
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Personalized Daughter Gift | Custom Quote Print | Graduation Gift For Daughter Wall Art",
        tags=["daughter gift", "graduation gift", "custom wall art", "daughter print",
              "mom to daughter", "personalized art", "mountain decor", "quote poster",
              "inspirational gift", "bedroom decor", "gift for her", "custom quote",
              "scenic wall art"],
        description_hook="This personalized daughter print is designed to make her feel seen, celebrated, and deeply loved. Every word is written just for her — a keepsake she will treasure long after the moment has passed.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="To My Daughter Canvas Print | Inspirational Wall Art | Daughter Birthday Gift From Mom",
        tags=["daughter canvas", "daughter birthday", "to my daughter", "wall art gift",
              "from mom gift", "daughter decor", "inspirational art", "canvas print",
              "gift from mom", "daughter room", "heartfelt gift", "birthday gift",
              "daughter keepsake"],
        description_hook="A canvas wrapped in words she needs to hear — strength, love, and a mother's endless pride. Give her a piece of art that speaks straight to her heart every single day.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Daughter Framed Print | Custom Name Wall Art | Sentimental Gift For Daughter From Dad",
        tags=["daughter framed", "framed wall art", "custom name art", "from dad gift",
              "daughter from dad", "sentimental gift", "personalized frame", "name print",
              "dad to daughter", "daughter decor", "gift ideas", "quote frame",
              "family wall art"],
        description_hook="A framed tribute to the daughter who has filled every room with light and every heart with joy. Custom-crafted with her name and your most heartfelt words, ready to hang and cherish forever.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Daughter Digital Print Download | Printable Wall Art | Instant Gift For Daughter",
        tags=["digital download", "printable art", "daughter print", "instant download",
              "daughter digital", "printable gift", "wall art print", "home decor",
              "daughter quote", "digital art", "bedroom print", "modern wall art",
              "affordable gift"],
        description_hook="Download, print, and frame in minutes — the perfect last-minute gift that looks anything but rushed. This printable daughter print delivers big emotion with beautiful design.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Daughter Graduation Wall Art | Class of 2025 Print | Personalized Grad Gift For Her",
        tags=["graduation print", "class of 2025", "grad wall art", "grad gift her",
              "daughter grad", "personalized grad", "college graduate", "university gift",
              "grad decor", "achievement art", "graduate print", "senior gift",
              "diploma frame"],
        description_hook="Celebrate her milestone with a print as extraordinary as she is — personalized with her name and the year she conquered everything she set out to do. This graduation wall art is a standing ovation in art form.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Daughter Moving Away Gift | New Home Wall Art | Daughter First Apartment Print",
        tags=["moving away gift", "new home print", "first apartment", "daughter moving",
              "going away gift", "new chapter art", "housewarming gift", "apartment decor",
              "daughter gift idea", "new beginning", "home wall art", "farewell gift",
              "daughter keepsake"],
        description_hook="When she moves into her own space, send a piece of home with her — a print that reminds her she's loved no matter the distance. This moving-away gift for daughters is warm, personal, and perfectly sized for any wall.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Daughter Wedding Day Gift | Bride Gift From Parents | To My Daughter On Her Wedding",
        tags=["wedding day gift", "bride gift", "daughter wedding", "from parents gift",
              "wedding wall art", "bridal gift", "wedding keepsake", "marriage gift",
              "daughter bride", "wedding print", "bridal shower", "family gift",
              "sentimental bride"],
        description_hook="On the day she says 'I do,' give her the gift of your words — a beautifully printed letter she will read through happy tears and keep for a lifetime. This wedding day gift for daughters is the one that will mean the most.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Personalized Daughter Gifts",
        title="Little Girl Room Wall Art | Daughter Nursery Print | Girls Bedroom Decor Poster",
        tags=["girls room decor", "nursery wall art", "little girl print", "girls bedroom",
              "daughter nursery", "kids room art", "toddler room", "girl decor",
              "nursery poster", "baby girl art", "pink wall art", "children decor",
              "girls print"],
        description_hook="Surround her with words that will grow with her — a gentle, beautiful print made for the little girl who already owns your whole heart. Soft colors and sweet sentiments make this the perfect addition to any girl's space.",
        price_tier="budget",
        product_type="poster",
    ),

    # ── SON GIFTS (6 templates) ──
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Personalized Son Gift | To My Son Wall Art Print | Inspirational Gift For Son From Mom",
        tags=["son gift", "to my son", "son wall art", "from mom son",
              "son print", "personalized son", "son birthday", "mom to son",
              "inspirational son", "son decor", "heartfelt son", "son keepsake",
              "gift for son"],
        description_hook="Every mother has words she carries in her heart — this print puts them on the wall where her son can see them every day. A personalized son gift that speaks volumes without saying a word.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Son Graduation Gift | Custom Quote Print For Son | College Grad Gift From Parents",
        tags=["son graduation", "grad gift son", "college grad son", "son grad print",
              "from parents son", "graduate son", "university son", "son milestone",
              "achievement son", "senior son", "grad decor son", "son canvas",
              "graduation decor"],
        description_hook="He worked hard, stayed focused, and earned every moment of this celebration — now give him a gift as impressive as his achievement. This son graduation print pairs beautifully with his diploma and hangs in any space.",
        price_tier="mid",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Son Wedding Day Gift | Groom Gift From Parents | To My Son On His Wedding Day Print",
        tags=["son wedding gift", "groom gift", "son wedding day", "wedding groom",
              "from parents groom", "son groom print", "wedding keepsake", "son marriage",
              "groom wall art", "wedding day art", "sentimental groom", "family wedding",
              "son bride groom"],
        description_hook="The day your son takes his vows is a day full of proud tears and overflowing love — let this print hold all the words you couldn't say at the altar. A framed gift he and his partner will display in their first home.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Son Birthday Gift Wall Art | Custom Name Print | Dad To Son Poster For Boys Room",
        tags=["son birthday", "boys room art", "dad to son", "custom name son",
              "son name print", "birthday son", "boys wall art", "teen boy decor",
              "son poster", "father son gift", "boy bedroom", "name wall art",
              "son from dad"],
        description_hook="A birthday gift that goes beyond the moment — a print that reminds him who he is, where he came from, and just how far he can go. Dad-approved words in a design built for a boy's room.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Son Moving Away Print | First Apartment Wall Art | Going To College Gift For Son",
        tags=["son moving gift", "college son gift", "going to college", "son apartment",
              "son dorm decor", "dorm wall art", "college gift son", "moving son",
              "new adventure son", "son first home", "dorm print", "college poster",
              "son going away"],
        description_hook="As he heads off to start the next chapter, send something that brings home with him — a print that says everything you'd say if you were standing right there. Perfect for dorm rooms, first apartments, or any new space he calls his own.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Personalized Son Gifts",
        title="Son Military Gift | Army Deployment Print | Proud Military Mom Son Wall Art",
        tags=["military son gift", "army son print", "military mom", "deployment gift",
              "proud military", "soldier gift", "patriotic son", "military art",
              "army wall art", "deployment art", "navy son gift", "marine gift",
              "military keepsake"],
        description_hook="For the son who chose to serve — a print that honors his courage, his sacrifice, and the family pride that follows him everywhere he goes. A military son gift worthy of the hero wearing the uniform.",
        price_tier="premium",
        product_type="framed",
    ),

    # ── WIFE / HUSBAND GIFTS (8 templates) ──
    ListingTemplate(
        niche="Wife Anniversary Gifts",
        title="To My Wife Anniversary Gift | Personalized Love Print | Wedding Anniversary Wall Art",
        tags=["wife anniversary", "anniversary gift", "to my wife", "love wall art",
              "personalized wife", "wedding gift", "couples art", "husband to wife",
              "anniversary print", "love print", "couples decor", "marriage gift",
              "romantic art"],
        description_hook="Every anniversary is a love story continued — this print captures the feeling of your first forever and every year since. A personalized wife anniversary gift she will hang close to her heart.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Wife Anniversary Gifts",
        title="Wife Valentine Gift | Love Quote Canvas Print | Romantic Gift For Wife Bedroom Decor",
        tags=["wife valentine", "valentine gift", "love canvas", "romantic gift",
              "wife gift idea", "couples canvas", "love decor", "bedroom decor",
              "valentine art", "love quote art", "wife birthday", "romantic decor",
              "couples gift"],
        description_hook="Valentine's Day calls for something that lasts longer than flowers — a canvas print filled with the words she deserves to hear every morning. Romantic, refined, and made to display proudly in your shared space.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Wife Anniversary Gifts",
        title="Just Because Gift For Wife | Surprise Love Print | Personalized Wife Wall Art Poster",
        tags=["just because gift", "surprise wife", "wife gift print", "love poster",
              "wife appreciation", "spontaneous gift", "wife wall art", "love art",
              "thoughtful gift", "wife home decor", "wife quote", "loving wife",
              "couple print"],
        description_hook="The best gifts need no occasion — just a reminder that you see her, love her, and appreciate every beautiful thing she does. This 'just because' wife print will catch her completely off guard in the best possible way.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Husband Anniversary Gifts",
        title="To My Husband Anniversary Print | Personalized Husband Gift | Love Wall Art For Him",
        tags=["husband gift", "to my husband", "anniversary him", "husband print",
              "wife to husband", "love art him", "husband decor", "couples art",
              "husband quote", "anniversary art", "husband wall art", "romantic him",
              "personalized him"],
        description_hook="He is your partner, your protector, and your favorite person — now tell him so with a print made just for him. This personalized husband anniversary gift goes far beyond any card.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Husband Anniversary Gifts",
        title="Husband Valentine Gift | Romantic Wall Art For Him | Love Quote Print Bedroom Decor",
        tags=["husband valentine", "romantic him", "valentine him", "love quote him",
              "husband gift idea", "bedroom art him", "couples bedroom", "love print him",
              "valentine poster", "man cave art", "study decor", "husband birthday",
              "love art couple"],
        description_hook="Skip the same old gift and give him something that makes him feel exactly as loved as he makes you feel. A romantic wall art print for him — clean design, powerful words, real emotion.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Husband Anniversary Gifts",
        title="5th Wedding Anniversary Gift | Wood Anniversary Print | Five Year Milestone Art",
        tags=["5th anniversary", "wood anniversary", "five year gift", "milestone gift",
              "wedding milestone", "anniversary five", "wood themed gift", "5 year art",
              "couples milestone", "wood decor", "anniversary print", "year five",
              "wedding five year"],
        description_hook="Five years of laughter, adventure, and choosing each other every single day — this wood-themed anniversary print honors every moment of that journey. A milestone gift as strong and beautiful as the marriage it celebrates.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Wife Anniversary Gifts",
        title="25th Silver Anniversary Gift | Silver Wedding Milestone | Personalized Couples Print",
        tags=["25th anniversary", "silver anniversary", "silver wedding", "25 years gift",
              "couples milestone", "silver gift", "anniversary 25", "milestone art",
              "silver decor", "wedding 25yr", "silver print", "vow renewal",
              "25 year couple"],
        description_hook="Twenty-five years of a love that has only deepened — a silver anniversary deserves a gift as rare and precious as what you have built together. This personalized couples print is the perfect centerpiece for your shared home.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Wife Anniversary Gifts",
        title="50th Golden Anniversary Gift | Gold Wedding Print | Fifty Year Celebration Wall Art",
        tags=["50th anniversary", "golden anniversary", "gold wedding", "50 years gift",
              "golden milestone", "fifty year art", "anniversary 50", "gold print",
              "golden decor", "50 year couple", "gold wall art", "vow renewal 50",
              "golden wedding"],
        description_hook="Fifty years of devotion, resilience, and unbreakable love — only the most meaningful gift will do for this golden milestone. A beautifully framed print that honors half a century of choosing each other.",
        price_tier="premium",
        product_type="framed",
    ),

    # ── MOM GIFTS (6 templates) ──
    ListingTemplate(
        niche="Mom Gifts",
        title="Mother's Day Gift | Personalized Mom Wall Art | Custom Quote Print For Mom From Kids",
        tags=["mothers day gift", "mom wall art", "personalized mom", "mom print",
              "gift from kids", "mom birthday", "mom decor", "mothers day print",
              "custom mom gift", "mom quote art", "mom keepsake", "mama gift",
              "children gift mom"],
        description_hook="There is no gift that can match everything she has given, but this personalized mom print comes beautifully close. Made with her name and your words, it is a Mother's Day gift she will hang in the place she loves most.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mom Gifts",
        title="Mom Birthday Gift | Custom Canvas For Mom | Sentimental Mother Art Print From Adult Child",
        tags=["mom birthday", "birthday mom", "canvas for mom", "mom canvas",
              "adult child mom", "sentimental mom", "mother canvas", "mom gift idea",
              "birthday canvas", "mother birthday", "gift for mama", "loving mom",
              "mom celebration"],
        description_hook="Her birthday is the perfect moment to tell her everything she means to you with art she can see every single day. This custom canvas for mom pairs stunning design with deeply personal words.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Mom Gifts",
        title="New Mom Gift | Baby Shower Wall Art | First Mother's Day Print For New Mother",
        tags=["new mom gift", "first mothers day", "baby shower gift", "new mother",
              "new baby art", "mama print", "new mom decor", "baby shower art",
              "first time mom", "nursery mom art", "mom newborn", "baby gift",
              "new mama decor"],
        description_hook="Welcome her into the most beautiful role she will ever hold — with a print that celebrates the love she already had before the baby even arrived. A new mom gift that honors the beginning of her greatest chapter.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mom Gifts",
        title="Mom Digital Print Download | Printable Mother Art | Instant Download Mom Quote Wall Art",
        tags=["mom digital", "printable mom", "instant mom gift", "digital mom print",
              "printable mother", "mom quote print", "download mom art", "mother digital",
              "home decor mom", "wall art mom", "digital gift mom", "printable quote",
              "budget mom gift"],
        description_hook="Download in seconds, print at home, and frame it yourself — a beautiful mom gift that looks custom and feels completely personal. No waiting, no shipping — just meaningful art ready when you need it.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Mom Gifts",
        title="Mama Bear Wall Art | Mom And Kids Print | Family Quote Poster For Mother's Home",
        tags=["mama bear art", "mom kids print", "family wall art", "mama decor",
              "mama bear decor", "family quote", "mother kids", "mom family",
              "bear family art", "family poster", "mama print", "home family art",
              "kids names mom"],
        description_hook="She is their fiercest protector and their softest landing — a mama bear print that captures the wild, unconditional love of motherhood perfectly. Display it in the kitchen, living room, or anywhere she rules the roost.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mom Gifts",
        title="Mom Sympathy Gift | In Memory Of Mother Print | Grief Healing Art For Loss Of Mom",
        tags=["mom sympathy", "loss of mom", "in memory mom", "grief healing",
              "memorial mom", "remembrance mom", "mom memorial", "bereavement gift",
              "condolence gift", "sympathy art", "heaven mom", "mom memory",
              "losing mom gift"],
        description_hook="When words fall short, a beautifully printed memorial tribute speaks the grief and the gratitude together. This in-memory-of-mom print offers comfort and a lasting way to honor her presence.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── DAD GIFTS (6 templates) ──
    ListingTemplate(
        niche="Dad Gifts",
        title="Father's Day Gift | Personalized Dad Wall Art | Custom Quote Print For Dad From Kids",
        tags=["fathers day gift", "dad wall art", "personalized dad", "dad print",
              "gift for dad", "dad birthday", "from kids dad", "dad quote art",
              "custom dad gift", "dad decor", "dad keepsake", "father gift",
              "father print"],
        description_hook="Dads don't always say what they feel, but this personalized print does the talking for the whole family. A Father's Day gift he will put up in his office, garage, or wherever he calls his own.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Dad Gifts",
        title="Dad Birthday Gift | Canvas Print For Dad | Sentimental Father Gift From Adult Child",
        tags=["dad birthday", "birthday dad", "canvas dad", "father canvas",
              "sentimental dad", "adult child dad", "loving father", "dad gift idea",
              "father birthday", "dad gift print", "gift for papa", "papa canvas",
              "dad celebration"],
        description_hook="This birthday canvas for dad is more than decoration — it is a permanent reminder that the work he put in as a father is seen, felt, and cherished. A sentimental gift he will tear up over (in the best way).",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Dad Gifts",
        title="Dad Man Cave Wall Art | Garage Decor For Dad | Funny Quote Poster For Dad's Workshop",
        tags=["man cave decor", "garage art dad", "dad workshop", "funny dad art",
              "man cave art", "workshop decor", "dad humor print", "garage wall art",
              "funny dad print", "dad cave", "shop decor dad", "man cave poster",
              "dad home art"],
        description_hook="Every man cave deserves a print that nails his personality — this garage and workshop wall art for dads is rugged, relatable, and just funny enough to make him smile every time. The perfect finishing touch for his domain.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Dad Gifts",
        title="Dad Digital Print | Printable Father Art | Instant Download Father's Day Wall Art",
        tags=["dad digital print", "printable dad", "instant dad gift", "digital father",
              "father digital", "printable father", "dad instant", "download dad art",
              "digital fathers day", "printable art dad", "fast gift dad", "budget dad",
              "dad print digital"],
        description_hook="A heartfelt Father's Day gift available for instant download — print it at home or at your local print shop in time for any occasion. Beautiful design, personal words, and zero shipping stress.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Dad Gifts",
        title="New Dad Gift | First Father's Day Print | Baby Announcement Wall Art For Dad",
        tags=["new dad gift", "first fathers day", "baby dad gift", "dad newborn",
              "new father print", "baby announcement", "daddy wall art", "dad baby",
              "first time dad", "new daddy gift", "baby shower dad", "expecting dad",
              "dad birth art"],
        description_hook="The moment he became 'Dad' changed everything — honor it with a print that captures the wonder, pride, and sheer joy of his brand-new role. A first Father's Day gift he will keep forever.",
        price_tier="mid",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Dad Gifts",
        title="Dad Fishing Wall Art | Fishing Lover Gift | Outdoor Dad Print For Lake House Decor",
        tags=["dad fishing gift", "fishing wall art", "lake house decor", "fishing decor",
              "outdoor dad", "fishing print", "lake art dad", "fisherman gift",
              "fishing poster", "cabin decor", "rod reel art", "bass fishing",
              "dad outdoors"],
        description_hook="For the dad who is happiest on the water — a fishing wall art print that captures his passion and looks stunning in any lake house, man cave, or cabin. Gift him the outdoors, even when he is indoors.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── GRANDPARENT GIFTS (6 templates) ──
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Grandma Gift | Personalized Grandchildren Names Print | Custom Grandmother Wall Art",
        tags=["grandma gift", "grandchildren names", "grandmother print", "nana gift",
              "personalized nana", "grandma wall art", "nana decor", "custom grandma",
              "family names art", "grandma keepsake", "nana print", "grandmother gift",
              "grandkids art"],
        description_hook="There is nothing she loves more than her grandchildren — except maybe seeing all their names beautifully printed in one place. This personalized grandma print is a gift she will show every visitor who comes through the door.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Grandpa Gift | Custom Grandfather Print | Personalized Papa Wall Art With Names",
        tags=["grandpa gift", "grandfather print", "papa gift", "custom grandpa",
              "personalized papa", "grandpa wall art", "grandpa decor", "papa decor",
              "grandchildren papa", "pops gift", "grandpa names", "grandfather art",
              "papa canvas"],
        description_hook="Papa deserves a gift as legendary as his stories — a personalized grandfather print featuring the names of every grandchild who calls him by that special title. A wall art gift that makes his heart swell with pride.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Grandparents Anniversary Gift | 50th Golden Anniversary | Grandma Grandpa Canvas Art",
        tags=["grandparents gift", "grandma grandpa", "50th anniversary", "golden couple",
              "grandparent art", "grandparent canvas", "family anniversary", "golden grandpa",
              "golden grandma", "milestone couple", "grandparents print", "family legacy",
              "elder couple art"],
        description_hook="Fifty years, a lifetime of memories, and a legacy of love that flows through every grandchild — this golden anniversary canvas is a tribute worthy of the family's greatest love story. A gift the whole family will cherish.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Nana Birthday Gift | Custom Nana Print | Personalized Grandmother Art From Grandkids",
        tags=["nana birthday", "birthday nana", "custom nana", "nana from kids",
              "grandkids nana", "nana art print", "nana celebration", "nana gift idea",
              "grandmother bday", "nana poster", "nana keepsake", "nana decor",
              "nana wall art"],
        description_hook="Her birthday is the perfect chance for the grandkids to say everything they feel — wrapped in a beautiful, personalized print made just for Nana. A birthday gift that will sit in her living room and make her smile every single day.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Grandma Christmas Gift | Holiday Print For Grandma | Christmas Grandchildren Art",
        tags=["grandma christmas", "christmas grandma", "holiday grandma", "xmas grandma",
              "christmas gift nan", "grandma holiday", "christmas family", "nana xmas",
              "holiday grandkids", "christmas decor", "family christmas", "nana christmas",
              "holiday art"],
        description_hook="Christmas morning just got more meaningful — a holiday print for grandma featuring every grandchild's name, wrapped in warmth and ready to hang by the tree. The gift she will reach for first every December.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Grandparent Gifts",
        title="Grandpa Fishing Gift | Grandpa Quote Print | Outdoor Grandpa Wall Art Cabin Decor",
        tags=["grandpa fishing", "grandpa outdoor", "fishing grandpa", "cabin grandpa",
              "grandpa nature", "outdoor print", "cabin wall art", "fishing art",
              "grandpa cabin", "lodge decor", "grandpa lake", "bass fishing art",
              "lake cabin"],
        description_hook="For the grandpa who lives for quiet mornings on the lake — a fishing quote print that honors his love of the outdoors and his role as the family's greatest storyteller. Perfect for his cabin, den, or garage wall.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── BEST FRIEND GIFTS (4 templates) ──
    ListingTemplate(
        niche="Best Friend Gifts",
        title="Best Friend Gift | Friendship Quote Wall Art | Personalized BFF Print For Best Friend",
        tags=["best friend gift", "bff gift", "friendship art", "friend quote",
              "bestie gift", "friend wall art", "personalized bff", "friend print",
              "friendship decor", "soul sister", "bff print", "friend keepsake",
              "bestie decor"],
        description_hook="Some friendships are rare, irreplaceable, and completely life-changing — this best friend print celebrates exactly that kind. A personalized wall art gift that tells her she is one of a kind and so is what you have.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Best Friend Gifts",
        title="Friendship Canvas Print | Soul Sister Wall Art | BFF Birthday Gift Canvas Poster",
        tags=["friendship canvas", "soul sister art", "bff birthday", "friend canvas",
              "bestie canvas", "sister friend", "bff wall art", "friend birthday",
              "soul sister gift", "canvas bestie", "birthday friend", "best friend bday",
              "friend decor"],
        description_hook="A canvas as colorful and layered as the friendship it celebrates — bold, warm, and full of the memories only the two of you share. Send this soul sister birthday gift and watch her beam.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Best Friend Gifts",
        title="Long Distance Friend Gift | Missing You Print | Thinking Of You Wall Art For Friend",
        tags=["long distance gift", "missing you art", "friend miles away", "distance friend",
              "thinking of you", "far away friend", "long distance art", "miles apart",
              "close in heart", "distance decor", "friend mail gift", "thinking art",
              "friend mail"],
        description_hook="Miles can separate you but they cannot dim what you share — this long-distance friend print is a daily reminder that the bond is alive no matter the zip code. Send it across the country and watch it close the gap.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Best Friend Gifts",
        title="Galentine's Day Gift | Girlfriends Wall Art | Squad Goals Print For Girl Friends",
        tags=["galentines gift", "girlfriends art", "squad print", "girls squad",
              "galentines day", "girl gang art", "squad goals", "girls decor",
              "friend squad", "girlfriend print", "girl tribe", "empowered women",
              "galentines art"],
        description_hook="Galentine's Day is for the women who show up, cheer loudest, and love hardest — this squad print celebrates every one of them. A girlfriend gift that belongs in the home of every woman with a true ride-or-die crew.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── CHRISTIAN WALL ART (10 templates) ──
    ListingTemplate(
        niche="Christian Wall Art",
        title="Christian Wall Art | Bible Verse Print | Scripture Home Decor Faith Quote Poster",
        tags=["christian art", "bible verse art", "scripture print", "faith wall art",
              "christian decor", "bible quote", "scripture decor", "faith poster",
              "christian home", "verse print", "jesus art", "worship decor",
              "spiritual art"],
        description_hook="Faith-centered homes deserve art that speaks truth on the walls — this Bible verse print brings scripture to life in a beautifully designed format. A Christian home decor piece that inspires everyone who walks through the door.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Prayer Wall Art | Christian Home Decor | Family Prayer Print Scripture Verse Poster",
        tags=["prayer wall art", "family prayer", "christian family", "prayer decor",
              "faith family art", "praying hands", "prayer poster", "christian verse",
              "home prayer", "faith decor", "prayer canvas", "scripture family",
              "christian canvas"],
        description_hook="A home grounded in prayer is a home filled with peace — this family prayer print is a daily reminder of where your strength comes from. Hang it in the entryway or living room and let it set the tone for every day.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Jeremiah 29:11 Print | Bible Verse Wall Art | Faith Scripture Poster Christian Gift",
        tags=["jeremiah 2911", "bible verse gift", "faith scripture", "christian poster",
              "hope future", "scripture gift", "verse 2911", "faith art gift",
              "christian print", "bible print", "hope wall art", "verse poster",
              "spiritual gift"],
        description_hook="Jeremiah 29:11 — plans for hope, for a future, and for a purpose beyond imagination. This scripture print is a daily anchor for believers who need the reminder that they are not walking alone.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Christian Nurse Gift | Faith And Healing Print | Nurse Scripture Art Hospital Decor",
        tags=["christian nurse", "nurse faith", "healing scripture", "nurse decor",
              "nurse gift faith", "hospital art", "nurse christian", "medical faith",
              "nurse bible", "caregiver art", "nurse scripture", "healing art",
              "faith nurse"],
        description_hook="For the nurse who treats the body and nurtures the soul — a faith-inspired print that honors both her calling and her Creator. A Christian nurse gift she will hang wherever she needs the most encouragement.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Christian Teacher Gift | Faith In Education Print | Teacher Scripture Wall Art",
        tags=["christian teacher", "teacher faith", "faith education", "teacher decor",
              "teacher scripture", "teacher bible", "educator faith", "teacher gift",
              "school faith art", "classroom faith", "teacher art", "christian edu",
              "teacher inspire"],
        description_hook="Teaching is a calling, and this Christian teacher print honors the sacred work of shaping young minds with patience and faith. A meaningful gift for any educator whose classroom runs on purpose and prayer.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Christian Dentist Gift | Faith Dental Print | Bible Verse For Dentist Office Decor",
        tags=["christian dentist", "dentist faith", "faith dental art", "dentist decor",
              "dentist bible", "dental faith", "dentist office art", "faith dentist",
              "dental scripture", "dental office", "christian dental", "dentist gift",
              "faith office art"],
        description_hook="Faith follows you into the operatory — this Christian dentist print is a quiet but powerful statement for any practice built on more than just teeth. A dental office decor piece that speaks to the heart of why you chose this career.",
        price_tier="mid",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="She Is Clothed In Strength Print | Proverbs 31 Art | Christian Woman Wall Decor",
        tags=["proverbs 31", "she is clothed", "strength dignity", "christian woman",
              "faith woman art", "proverbs art", "strength art", "woman faith",
              "christian her", "brave woman art", "strength decor", "proverbs print",
              "virtuous woman"],
        description_hook="Proverbs 31 is more than a verse — it is a declaration of the strength, dignity, and grace that every faithful woman carries. This beautifully designed print is a gift worthy of any woman who lives those words.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Be Still And Know Print | Psalm 46:10 Wall Art | Christian Meditation Decor Gift",
        tags=["be still know", "psalm 4610", "meditation art", "christian calm",
              "stillness art", "peace scripture", "calm decor", "be still print",
              "psalm art", "faith peace", "quiet faith", "restful art",
              "christian peace"],
        description_hook="In a world of noise, this verse is a command and a comfort — be still, breathe, and know. This Psalm 46:10 print is a calming presence in any room where peace is needed most.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Trust In The Lord Print | Proverbs 3:5 Art | Bible Verse Canvas Christian Home",
        tags=["trust in lord", "proverbs 3 5", "lean not own", "trust scripture",
              "faith trust art", "trust canvas", "proverbs canvas", "faith home decor",
              "christian trust", "bible canvas", "scripture canvas", "trust verse",
              "faith lean art"],
        description_hook="Proverbs 3:5 is the daily reminder that control is an illusion — trust is the anchor. This Trust in the Lord canvas is a stunning and spiritually grounding piece for any faith-centered home.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Christian Wall Art",
        title="Cross Wall Art | Christian Cross Print | Jesus Saves Faith Decor Inspirational",
        tags=["cross wall art", "christian cross", "jesus saves", "cross decor",
              "faith cross", "cross print", "christian poster", "cross art",
              "Jesus art", "worship art", "cross canvas", "holy art",
              "redemption art"],
        description_hook="The cross is the center of everything — a timeless symbol of grace, redemption, and unwavering love. This Christian cross wall art brings that meaning into your home with bold, beautiful design.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── GRADUATION GIFTS (8 templates) ──
    ListingTemplate(
        niche="Graduation Gifts",
        title="Graduation Gift | Class of 2025 Wall Art | Personalized Grad Print Inspirational",
        tags=["graduation gift", "class of 2025", "grad wall art", "graduate print",
              "graduation decor", "grad poster", "senior 2025", "class of 25",
              "graduate gift", "grad keepsake", "grad quote", "achievement art",
              "diploma gift"],
        description_hook="She wore the cap and crossed the stage — now give her a wall art print that matches the magnitude of what she has accomplished. A personalized graduation gift that will follow her from dorm to first apartment to forever home.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="Dental School Graduation Gift | DMD DDS Graduate Print | Dentist Grad Wall Art",
        tags=["dental grad gift", "dentist graduate", "DMD graduate", "DDS graduate",
              "dental school art", "dentist grad", "dental milestone", "dmd print",
              "dds wall art", "dentist decor", "new dentist", "dental degree",
              "dental office art"],
        description_hook="Four years of science, sleepless nights, and hands-on precision have led to this — Dr. [Name] is ready for the operatory. This dental school graduation gift marks the moment the dream became a reality.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="Medical School Graduation Gift | MD Graduate Print | Doctor Grad Wall Art Decor",
        tags=["medical grad gift", "doctor graduate", "MD graduate", "med school art",
              "doctor grad", "medical degree", "new doctor", "physician grad",
              "doctor decor", "medical milestone", "MD wall art", "residency gift",
              "dr degree art"],
        description_hook="Medical school is one of the hardest journeys a person can undertake — and this MD graduation print honors every sacrifice made along the way. A doctor grad gift worthy of the white coat she just earned.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="Nursing School Graduation Gift | RN Graduate Print | Nurse Grad Wall Art Decor",
        tags=["nursing grad gift", "RN graduate", "nurse grad", "nursing school art",
              "new nurse print", "RN wall art", "nurse milestone", "nursing degree",
              "nurse decor", "NCLEX gift", "nurse achievement", "RN decor",
              "nursing grad art"],
        description_hook="The NCLEX is passed, the scrubs are on, and the calling is answered — now celebrate the new RN in your life with a nursing graduation print that honors every long shift it took to get here. A nurse grad gift she will hang with pride.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="Law School Graduation Gift | JD Graduate Print | Lawyer Grad Wall Art Decor",
        tags=["law school grad", "JD graduate", "lawyer grad", "law school art",
              "new lawyer print", "JD wall art", "bar exam gift", "attorney grad",
              "law degree art", "lawyer decor", "esquire art", "attorney print",
              "law grad gift"],
        description_hook="Three years of case law, moot court, and late-night studying have earned her the right to say 'counselor' — and this JD graduation print says it in style. A law school grad gift that looks as sharp as she does.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="Engineering Graduation Gift | Engineer Grad Print | STEM Graduate Wall Art Decor",
        tags=["engineering grad", "engineer gift", "STEM graduate", "tech grad",
              "engineer wall art", "engineering art", "new engineer", "STEM art",
              "engineering print", "engineer decor", "grad STEM", "tech milestone",
              "engineer degree"],
        description_hook="Four years of problem-solving, late-night labs, and building things that matter — this engineer graduation print celebrates the mind that turned theory into reality. A STEM grad gift as strong as the structures he designs.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="High School Graduation Gift | Senior Wall Art | Class of 2025 Inspiration Print",
        tags=["hs graduation", "high school grad", "senior gift", "senior wall art",
              "class 2025 art", "teen grad gift", "18th birthday", "senior print",
              "graduation teen", "senior milestone", "high school art", "grad teen",
              "teen achievement"],
        description_hook="High school is just the launchpad — this senior graduation print is a reminder that the biggest adventures are still ahead. A class of 2025 wall art gift for the teen who is ready to take on the world.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Graduation Gifts",
        title="College Graduation Gift Canvas | University Grad Art | Bachelor Degree Graduate Print",
        tags=["college grad gift", "university grad", "bachelor degree", "college canvas",
              "grad canvas art", "degree canvas", "college milestone", "college art",
              "bachelor art", "university print", "college graduate", "bachelor grad",
              "campus grad art"],
        description_hook="Four years of growth, discovery, and becoming — this college graduation canvas honors the whole journey, not just the diploma. A university grad gift that looks stunning in a new apartment, office, or home.",
        price_tier="premium",
        product_type="canvas",
    ),

    # ── MEMORIAL / SYMPATHY (6 templates) ──
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="Pet Memorial Print | Dog Memorial Wall Art | In Loving Memory Dog Gift Sympathy",
        tags=["pet memorial", "dog memorial", "in memory dog", "pet loss gift",
              "dog sympathy", "pet tribute", "dog rainbow bridge", "memorial dog",
              "dog loss art", "pet grief", "beloved dog", "dog forever",
              "pet memory art"],
        description_hook="A dog leaves paw prints on every part of your heart — this pet memorial print captures the love, the joy, and the quiet ache of missing a good dog. A sympathy gift that honors the bond that never really ends.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="Cat Memorial Print | In Memory Of Cat Wall Art | Pet Loss Sympathy Gift Cat Lover",
        tags=["cat memorial", "in memory cat", "cat loss gift", "cat sympathy",
              "cat tribute", "cat rainbow", "memorial cat art", "cat grief",
              "beloved cat", "cat memory", "cat forever", "pet loss cat",
              "feline memorial"],
        description_hook="Cats choose their people, and losing yours leaves a silence only she could fill — this cat memorial print is a tender tribute to the purrs, the cuddles, and the irreplaceable companionship. A gift of comfort for any cat lover in grief.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="In Memory Of Person Print | Memorial Wall Art | Sympathy Gift Grief Healing Decor",
        tags=["memorial print", "in memory of", "sympathy gift", "grief healing",
              "condolence art", "bereavement gift", "memory wall art", "loss gift",
              "grief decor", "remembrance art", "loved one art", "heaven tribute",
              "memorial decor"],
        description_hook="Grief is love with nowhere to go — this memorial print gives it a beautiful place to rest. A sympathy gift that honors the memory of someone irreplaceable and provides comfort through art.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="Grief Healing Wall Art | Loss Comfort Print | Sympathy Gift For Grieving Person",
        tags=["grief healing art", "comfort print", "loss healing", "grief art",
              "sympathy healing", "grief comfort", "healing decor", "loss comfort",
              "grief support", "bereavement art", "healing gift", "grief print",
              "comfort decor"],
        description_hook="Healing is not linear, and grief is not a sign of weakness — it is a testament to how deeply you loved. This healing-focused sympathy print offers quiet comfort and a gentle reminder that you are not alone in this.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="Golden Retriever Memorial Print | Dog Loss Art | In Memory Golden Retriever Gift",
        tags=["golden retriever", "golden memorial", "retriever loss", "golden tribute",
              "dog loss art", "golden decor", "retriever print", "golden gift",
              "golden sympathy", "dog memorial art", "forever golden", "pet loss",
              "golden memory"],
        description_hook="Golden retrievers leave golden hearts forever changed — this memorial print is a tribute to the most loyal, joyful companion a family could have. A golden retriever loss gift that brings tears and a smile at the very same time.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Memorial Sympathy Gifts",
        title="Father Memorial Print | In Memory Of Dad | Loss Of Father Sympathy Art Wall Decor",
        tags=["father memorial", "dad memorial", "in memory dad", "loss of father",
              "dad sympathy", "father tribute", "dad memory art", "missing dad",
              "father heaven", "dad forever", "grief dad", "dad loss gift",
              "memorial father"],
        description_hook="He was your first hero, your safe harbor, and the steady presence you could always count on — this father memorial print honors the man who shaped everything you are. A loss-of-father sympathy gift that holds space for the grief and the gratitude.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── FUTURE PROFESSION (8 templates) ──
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Dentist Print | Dental Student Gift | Pre-Dental Motivation Wall Art Decor",
        tags=["future dentist", "dental student", "pre-dental", "dentist gift",
              "dental school", "dental student art", "dentist motivation", "DAT prep",
              "dental decor", "future dds", "dental art", "aspiring dentist",
              "dental inspiration"],
        description_hook="Every late-night study session, every practice question, every DAT prep hour is building toward the moment she puts on the white coat — this future dentist print is the daily reminder that the goal is worth it. A dental student gift that fuels the fire.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Doctor Print | Pre-Med Student Gift | Medical School Motivation Wall Art",
        tags=["future doctor", "pre-med gift", "medical student", "aspiring doctor",
              "doctor motivation", "med school art", "pre med decor", "future MD",
              "MCAT motivation", "doctor dream", "medical art", "future physician",
              "med student"],
        description_hook="The road to MD is long, demanding, and completely worth it — this future doctor print is fuel for the dream on the hardest study days. A pre-med student gift that says 'you've got this' in the most beautiful way.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Nurse Print | Nursing Student Gift | NCLEX Motivation Wall Art For Student",
        tags=["future nurse", "nursing student", "aspiring nurse", "RN student",
              "NCLEX motivation", "nurse student art", "future RN", "nursing school",
              "nurse dream", "nursing decor", "future nursing", "student nurse",
              "nurse motivation"],
        description_hook="Nursing school is one of the hardest things she will ever do — and one of the most rewarding. This future nurse print is a daily push through the long lectures, clinical hours, and NCLEX prep that stand between her and the scrubs she was born to wear.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Teacher Print | Education Student Gift | Teaching Motivation Wall Art Decor",
        tags=["future teacher", "teacher student", "aspiring teacher", "education gift",
              "teacher motivation", "teaching student", "future educator", "student teacher",
              "teaching art", "teacher dream", "edu student", "classroom future",
              "teacher inspire"],
        description_hook="She chose teaching because she believes every child deserves someone in their corner — this future teacher print celebrates that calling before the first bell ever rings. A student teacher gift as inspiring as she is.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Lawyer Print | Law Student Gift | Bar Exam Motivation Wall Art Decor",
        tags=["future lawyer", "law student", "aspiring lawyer", "bar exam",
              "law school art", "future JD", "lawyer motivation", "pre-law gift",
              "law student art", "attorney dream", "bar prep", "future attorney",
              "law motivation"],
        description_hook="Law school is where arguments are built, minds are sharpened, and futures are forged — this future lawyer print hangs in the study of someone with the grit to pass the bar and change lives. A law student gift that belongs on every aspiring attorney's wall.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Engineer Print | STEM Student Gift | Engineering Motivation Desk Wall Art",
        tags=["future engineer", "STEM student", "engineering gift", "aspiring engineer",
              "tech student", "engineering art", "future STEM", "engineer student",
              "tech motivation", "engineer dream", "STEM motivation", "engineer decor",
              "engineering decor"],
        description_hook="Every equation solved, every project completed, and every late-night lab session is building the engineer the world needs — this future engineer print says so, loud and proud. A STEM student gift that motivates long after finals week.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future Veterinarian Print | Vet Student Gift | Veterinary School Motivation Art",
        tags=["future vet", "vet student", "veterinary gift", "aspiring vet",
              "vet school art", "future DVM", "vet motivation", "animal doctor",
              "vet student art", "veterinary art", "DVM student", "animal care",
              "vet dream"],
        description_hook="She chose to heal animals because compassion knows no species — this future veterinarian print is a tribute to the hardest-working, most-caring student in the room. A vet student gift she will hang in the clinic one day.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Future Profession Gifts",
        title="Future PA Print | Physician Assistant Student Gift | PA School Motivation Wall Art",
        tags=["future PA", "PA student", "physician assistant", "PA school art",
              "aspiring PA", "PA motivation", "future physician", "PA student gift",
              "healthcare student", "PA decor", "PANCE prep", "PA program",
              "PA school gift"],
        description_hook="PA school demands everything you have — and this future PA print reminds you on the toughest days exactly why you signed up for this incredible journey. A physician assistant student gift full of purpose and power.",
        price_tier="budget",
        product_type="poster",
    ),

    # ── DENTAL SCHOOL NICHE (6 templates) ──
    ListingTemplate(
        niche="Dental School Niche",
        title="DAT Motivation Print | Dental Admissions Test Art | Pre-Dental Student Wall Decor",
        tags=["DAT motivation", "dental admissions", "DAT prep art", "pre-dental art",
              "dental test", "DAT student", "dental exam", "DAT decor",
              "dental score", "pre dental", "dental study", "admissions prep",
              "dental student"],
        description_hook="The DAT is the first door — and you have everything it takes to open it. This DAT motivation print is the daily reminder to sharpen your pencil, trust your preparation, and keep pushing toward the dental school of your dreams.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Dental School Niche",
        title="Dental Boards Motivation Print | NBDE INBDE Art | Dental Student Exam Decor",
        tags=["dental boards", "NBDE motivation", "INBDE art", "board exam",
              "dental exam art", "board prep", "dental licensing", "boards decor",
              "dental milestone", "board study", "dental licensure", "dentist boards",
              "exam motivation"],
        description_hook="The boards stand between you and the clinic — but you have prepared for this. This dental boards motivation print is the battle cry for the final push toward licensure and the career you have worked so hard to earn.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Dental School Niche",
        title="White Coat Ceremony Gift | Dental Student White Coat | New Dentist Print Gift",
        tags=["white coat gift", "dental white coat", "white coat art", "dentist coat",
              "dental ceremony", "white coat print", "new dentist", "coat ceremony",
              "dentist milestone", "dental rite", "dental ritual", "coat decor",
              "dentist student"],
        description_hook="The white coat is more than fabric — it is a symbol of the oath you are taking and the patients who will trust you with their care. This white coat ceremony print is a gift worthy of one of dentistry's most meaningful milestones.",
        price_tier="mid",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Dental School Niche",
        title="Dental Practice Owner Gift | Private Practice Print | Dentist Opening Day Art",
        tags=["practice owner", "dental practice", "opening day art", "new practice",
              "dentist owner", "private practice", "dental business", "dentist open",
              "practice decor", "dental office", "grand opening", "new office",
              "dentist business"],
        description_hook="Opening your own practice is the dream most dentists have from day one — and this dental practice owner print celebrates the day that dream became a reality. Hang it in the reception area and let every patient see what you stand for.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Dental School Niche",
        title="Dental Student Graduation Canvas | DDS DMD Graduate | Dental Degree Canvas Gift",
        tags=["dental graduation", "DDS canvas", "DMD canvas", "dental degree",
              "dental grad art", "dentist canvas", "dental school end", "new DDS",
              "new DMD", "dental canvas", "dentist decor", "dental grad canvas",
              "dentist gift"],
        description_hook="Four years of crown preps, root canals, and restorations — and now the degree is official. This dental graduation canvas is a beautiful statement piece for the new DDS or DMD who is ready to change smiles and change lives.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Dental School Niche",
        title="Dentist Motivational Print | Dental Office Decor | Dentist Inspiration Wall Art",
        tags=["dentist motivation", "dental office art", "dentist office", "dental inspire",
              "dentist decor", "practice art", "dental wall art", "dentist inspire",
              "office motivation", "dental decor", "dentistry art", "dental poster",
              "dentist print"],
        description_hook="Your dental office should reflect the care, precision, and passion you bring to every patient — this motivational dentist print does exactly that. Hang it in the operatory or consultation room and let it speak for the practice you have built.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── HEALTHCARE WORKERS (6 templates) ──
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="ICU Nurse Gift | Critical Care Nurse Print | Intensive Care Wall Art Nurse Decor",
        tags=["ICU nurse gift", "critical care", "ICU wall art", "ICU decor",
              "nurse ICU", "critical nurse", "intensive care", "ICU print",
              "nurse critical", "care nurse art", "ICU nurse art", "hospital decor",
              "ICU motivation"],
        description_hook="ICU nurses carry the weight of the most critical moments in a patient's life — this print honors the calm, skilled, and compassionate hands that make miracles look routine. An ICU nurse gift as extraordinary as the care they provide.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="NICU Nurse Gift | Newborn ICU Nurse Print | Neonatal Nurse Wall Art Decor",
        tags=["NICU nurse", "newborn nurse", "neonatal nurse", "NICU gift",
              "neonatal art", "NICU decor", "NICU print", "baby nurse",
              "preemie nurse", "NICU art", "nurse newborn", "tiny babies",
              "neonatal gift"],
        description_hook="NICU nurses give the smallest patients their greatest fighting chance — a profession that demands extraordinary skill and an even bigger heart. This NICU nurse gift is a tribute to the angels in scrubs who watch over the tiniest miracles.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="Physical Therapist Gift | PT Wall Art | Physiotherapy Motivational Print Decor",
        tags=["PT gift", "physical therapy", "physiotherapy art", "therapist print",
              "PT decor", "rehab art", "PT wall art", "physical therapist",
              "therapy decor", "PT motivation", "rehab decor", "therapist gift",
              "PT art print"],
        description_hook="Physical therapists turn pain into progress, setbacks into strength, and recovery into triumph — one session at a time. This PT wall art print is a motivational gift for the physical therapist who changes lives through movement.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="Pharmacist Gift | Pharmacy Wall Art Print | RPh PharmD Motivational Decor",
        tags=["pharmacist gift", "pharmacy art", "RPh print", "PharmD gift",
              "pharmacist decor", "pharmacy decor", "RPh art", "pharmacy print",
              "pharmacist art", "drug safety art", "medication art", "PharmD decor",
              "pharmacy wall"],
        description_hook="The pharmacist is the last line of safety and the first person patients trust with their questions — this pharmacy wall art print honors the expertise behind every prescription. A pharmacist gift that says 'your work matters more than most people know.'",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="Occupational Therapist Gift | OT Wall Art | Therapy Motivational Print Decor",
        tags=["OT gift", "occupational therapy", "OT wall art", "OT decor",
              "therapy gift", "OT motivation", "OT print", "rehab OT",
              "OT art print", "daily living", "OT therapist", "occupational art",
              "function art"],
        description_hook="Occupational therapists help people rebuild the everyday moments that make life meaningful — that is a kind of healing that goes beyond the clinical. This OT wall art print is a beautifully designed tribute to the therapist who gives life back.",
        price_tier="budget",
        product_type="digital",
    ),
    ListingTemplate(
        niche="Healthcare Worker Gifts",
        title="Radiologist Gift | X-Ray Wall Art | Radiology Motivational Print Decor",
        tags=["radiologist gift", "radiology art", "x-ray art", "radiologist decor",
              "xray wall art", "radiology print", "imaging art", "radiology gift",
              "radiologist art", "diagnostic art", "x ray print", "scan art",
              "radiology decor"],
        description_hook="Radiologists see what others cannot — finding the answers hidden in film and pixels that change the course of a patient's care. This radiology wall art print celebrates the diagnostic genius behind every read and every report.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── PET LOVERS (4 templates) ──
    ListingTemplate(
        niche="Pet Lover Gifts",
        title="Dog Lover Wall Art | Dog Quote Print | Pet Owner Gift Dog Decor Home Poster",
        tags=["dog lover art", "dog wall art", "dog quote", "pet lover gift",
              "dog decor", "dog owner", "dog poster", "dog art print",
              "dog home decor", "puppy art", "dog life", "dog gift",
              "dog print"],
        description_hook="Life is short but a dog's love makes every second count — this dog lover wall art print is a celebration of the four-legged family member who fills your home with joy. The perfect gift for any dog parent who wears that title with pride.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Pet Lover Gifts",
        title="Cat Lover Wall Art | Cat Quote Print | Crazy Cat Lady Gift Home Decor Poster",
        tags=["cat lover art", "cat wall art", "cat quote", "cat lady gift",
              "cat decor", "cat owner", "cat poster", "cat art print",
              "cat home decor", "kitten art", "crazy cat lady", "cat gift",
              "cat print"],
        description_hook="There is no love quite like the love of a cat — conditional, mysterious, and completely irresistible. This cat lover wall art print is a badge of honor for the proudest cat parent in the room.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Pet Lover Gifts",
        title="Golden Retriever Wall Art | Golden Retriever Print | Dog Breed Art Pet Decor Gift",
        tags=["golden retriever", "retriever art", "golden print", "dog breed art",
              "golden decor", "retriever gift", "golden dog", "breed art",
              "dog lover", "golden owner", "retriever decor", "dog portrait",
              "golden art"],
        description_hook="Golden retrievers do not just live in your home — they live in your heart permanently, wag-first and fully. This golden retriever wall art print is a joyful tribute to the breed that perfected unconditional love.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Pet Lover Gifts",
        title="Dog Memorial Canvas | Beloved Dog Loss Art | Dog Rainbow Bridge Canvas Print",
        tags=["dog memorial", "rainbow bridge", "dog loss art", "memorial canvas",
              "dog tribute", "beloved dog", "dog grief", "pet loss canvas",
              "dog heaven art", "dog forever", "memorial print", "dog sympathy",
              "dog canvas"],
        description_hook="The rainbow bridge is where good dogs wait — and your good dog deserves a tribute as beautiful as the love you shared. This dog memorial canvas is a stunning, healing piece that keeps their memory alive on your wall.",
        price_tier="premium",
        product_type="canvas",
    ),

    # ── WEDDING / ANNIVERSARY (6 templates) ──
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="Wedding Gift | Personalized Couples Wall Art | Mr And Mrs Print Wedding Decor",
        tags=["wedding gift", "couples wall art", "mr and mrs", "wedding art",
              "wedding decor", "couple print", "bridal gift", "wedding keepsake",
              "wedding poster", "newlywed gift", "wedding home", "couple art",
              "wedding print"],
        description_hook="The wedding day is just the beginning of the most beautiful story they will ever write — this personalized couples print is the perfect gift to hang in their first home together. Meaningful, elegant, and completely theirs.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="1st Anniversary Gift | Paper Anniversary Print | First Anniversary Art Couple",
        tags=["first anniversary", "1st anniversary", "paper anniversary", "year one",
              "anniversary one", "paper gift", "first year art", "paper decor",
              "anniversary gift", "one year art", "couple year", "year one art",
              "paper print"],
        description_hook="One year ago you made a promise — and every day since has been proof that you meant every word. This paper anniversary print is a first-year gift as personal and beautiful as the love it celebrates.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="10th Anniversary Gift | Tin Anniversary Print | Ten Years Milestone Couple Art",
        tags=["10th anniversary", "tin anniversary", "ten years gift", "decade gift",
              "anniversary 10", "10 year couple", "milestone art", "ten year art",
              "decade couple", "tin gift", "10 years art", "year ten",
              "decade decor"],
        description_hook="Ten years of choosing each other, growing together, and building something real — this tin anniversary print is a tribute to a decade of extraordinary love. A milestone gift as enduring as the marriage it honors.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="Wedding Vows Print | Custom Vows Wall Art | Personalized Wedding Vow Art Couple",
        tags=["wedding vows art", "custom vows", "vow print", "personalized vows",
              "vows wall art", "custom vow art", "wedding words", "vow decor",
              "couple vows", "ceremony art", "vow keepsake", "wedding words art",
              "vow poster"],
        description_hook="Your wedding vows were the most personal words ever spoken between you — now put them on the wall where you can see them every morning. This custom wedding vows print transforms your actual ceremony words into stunning wall art.",
        price_tier="premium",
        product_type="framed",
    ),
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="Newlywed Gift | Couples Home Decor | Personalized First Home Print Mr Mrs Art",
        tags=["newlywed gift", "first home art", "couple home", "mr mrs decor",
              "newlywed decor", "home couple art", "first home print", "couple decor",
              "housewarming couple", "newlywed print", "couple home art", "first home",
              "newlywed home"],
        description_hook="Their first home together deserves art that is just as personal as the love they bring into it — this newlywed print is a beautifully designed reminder of who they are and what they are building. A first-home gift that grows with them.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Wedding Anniversary Gifts",
        title="Love Story Print | How We Met Wall Art | Personalized Couple Story Map Art",
        tags=["love story art", "how we met", "couple story", "love map art",
              "couple timeline", "our story print", "personalized love", "couple map",
              "love journey", "story art", "couple history", "love narrative",
              "our story art"],
        description_hook="Every love story is worth telling — this personalized couple story print maps the moments that matter most in a beautifully designed layout. From first date to 'I do,' it captures the whole journey in one stunning wall art piece.",
        price_tier="premium",
        product_type="framed",
    ),

    # ── NEW BABY / PARENTS (4 templates) ──
    ListingTemplate(
        niche="New Baby Gifts",
        title="Baby Shower Gift | Nursery Wall Art | Personalized New Baby Print Birth Stats Art",
        tags=["baby shower gift", "nursery art", "new baby print", "birth stats",
              "baby decor", "nursery decor", "baby name art", "birth date print",
              "newborn art", "baby wall art", "baby keepsake", "shower gift",
              "baby stats"],
        description_hook="Every baby deserves to come home to a nursery filled with love and beauty — this personalized birth stats print captures the exact moment they arrived and makes it a piece of art forever. The ultimate baby shower gift for new parents.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="New Baby Gifts",
        title="New Mom Gift | Motherhood Wall Art | First Time Mom Print Nursery Decor Gift",
        tags=["new mom gift", "motherhood art", "first time mom", "new mother",
              "mom nursery", "mama art", "new mama", "motherhood print",
              "mom decor", "mama decor", "baby shower mom", "new mom decor",
              "motherhood decor"],
        description_hook="Becoming a mother for the first time is the most overwhelming, beautiful, and life-altering thing a woman can experience — this new mom print honors every emotion of that sacred beginning. A first-time mom gift that says 'you are doing it perfectly.'",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="New Baby Gifts",
        title="New Dad Gift | First Father's Day Print | Dad And Baby Wall Art Nursery Decor",
        tags=["new dad gift", "first fathers day", "dad baby art", "father baby",
              "dad nursery", "new father", "first dad gift", "daddy art",
              "dad decor", "papa baby", "new papa", "daddy print",
              "dad baby decor"],
        description_hook="The moment he held that baby, everything changed — this first dad print captures the awe, the pride, and the new-found purpose that only fatherhood can give. A new dad gift for the man who just became someone's whole world.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="New Baby Gifts",
        title="Birth Announcement Art | Baby Name Print | Custom Birth Details Wall Art Nursery",
        tags=["birth announcement", "baby name print", "birth details", "custom baby",
              "name nursery", "birth art", "baby birth print", "nursery name",
              "birth keepsake", "baby name art", "birth poster", "name decor",
              "baby custom art"],
        description_hook="Their name, their birthday, their weight, their length — all the details that made the day unforgettable, beautifully arranged into nursery wall art. A custom birth announcement print that will hang in their room from day one to forever.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── MENTAL HEALTH (4 templates) ──
    ListingTemplate(
        niche="Mental Health Art",
        title="Mental Health Art | Anxiety Healing Print | Self-Love Wall Art Inspirational Decor",
        tags=["mental health art", "anxiety healing", "self love art", "healing print",
              "anxiety decor", "self care art", "mental wellness", "healing decor",
              "self worth art", "anxiety art", "calm art", "wellness decor",
              "healing wall art"],
        description_hook="Healing is brave, progress is non-linear, and you are stronger than the anxiety that tries to tell you otherwise — this mental health print is a daily reminder of your worth. A self-love wall art piece for anyone on the beautiful, hard journey of healing.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mental Health Art",
        title="Grief Healing Print | Loss Comfort Wall Art | You Are Not Alone Sympathy Art",
        tags=["grief print", "healing art", "loss comfort", "grief comfort",
              "grief wall art", "not alone art", "healing poster", "grief decor",
              "comfort art", "grief healing", "loss art", "grief support",
              "healing quote"],
        description_hook="Grief is not something you get over — it is something you carry with more grace as time passes. This grief healing print wraps you in the reminder that your pain is valid, your love was real, and you are not walking this road alone.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mental Health Art",
        title="Recovery Wall Art | Sobriety Gift Print | Sober Life Motivation Art Decor",
        tags=["recovery art", "sobriety gift", "sober life art", "recovery print",
              "sobriety decor", "sober art", "recovery decor", "clean sober",
              "sobriety print", "recovery quote", "sober motivation", "strength art",
              "recovery gift"],
        description_hook="Recovery takes more courage than most people will ever understand — this sobriety print is a powerful daily statement of the life you are choosing and the strength it takes to choose it every single day. A recovery gift that means everything.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Mental Health Art",
        title="Self Love Print | You Are Enough Wall Art | Positive Affirmation Decor For Bedroom",
        tags=["self love print", "you are enough", "affirmation art", "positive art",
              "self worth", "enough art", "affirmation print", "self esteem",
              "bedroom decor", "positive decor", "self care print", "worth art",
              "affirmation decor"],
        description_hook="In a world that tells you to be more, do more, and have more — this print is the quiet but fierce reminder that you are already enough, exactly as you are. A self-love wall art piece for every bedroom, bathroom mirror, or desk corner that needs a daily dose of truth.",
        price_tier="budget",
        product_type="digital",
    ),

    # ── FITNESS / GYM (4 templates) ──
    ListingTemplate(
        niche="Fitness Gym Decor",
        title="Home Gym Wall Art | Workout Motivation Print | Fitness Decor Gym Quote Poster",
        tags=["home gym art", "workout print", "gym motivation", "fitness decor",
              "gym wall art", "workout decor", "exercise art", "gym quote",
              "fitness print", "workout poster", "gym poster", "gym decor",
              "fitness art"],
        description_hook="Every rep, every set, and every drop of sweat in your home gym is building the version of you that refuses to quit — this workout motivation print is the energy on your wall that matches the energy in your training. Hang it where you need it most.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Fitness Gym Decor",
        title="Running Wall Art | Runner Motivation Print | Marathon Runner Gift Decor Poster",
        tags=["running art", "runner gift", "marathon art", "running decor",
              "runner print", "marathon gift", "run motivation", "runner wall art",
              "running poster", "5K art", "marathon print", "run decor",
              "runner motivation"],
        description_hook="Miles are just numbers until they become the distance between who you were and who you are becoming — this runner motivation print captures that truth beautifully. A marathon runner gift for the person who runs toward their goals, literally.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Fitness Gym Decor",
        title="Bodybuilding Wall Art | Gym Motivation Canvas | Powerlifting Fitness Decor Print",
        tags=["bodybuilding art", "gym canvas", "powerlifting art", "lifting decor",
              "gym motivation", "bodybuilder gift", "lifting print", "power lift",
              "gym canvas art", "iron game", "muscle art", "lifting motivation",
              "gains decor"],
        description_hook="The iron teaches you more about discipline, grit, and self-belief than almost anything else in life — this bodybuilding wall art canvas is a tribute to the lifestyle that demands everything and gives back more. A gym motivation gift for the lifter who lives it.",
        price_tier="premium",
        product_type="canvas",
    ),
    ListingTemplate(
        niche="Fitness Gym Decor",
        title="Yoga Wall Art | Mindful Movement Print | Yoga Studio Decor Meditation Poster",
        tags=["yoga wall art", "yoga decor", "yoga print", "yoga studio",
              "meditation art", "mindful art", "yoga poster", "yoga gift",
              "yoga motivation", "studio decor", "namaste art", "yoga quote",
              "mindful decor"],
        description_hook="Yoga is the practice of coming home to yourself — breath by breath, pose by pose, and moment by present moment. This yoga wall art print is a peaceful, beautiful anchor for any studio, practice space, or mindful corner of your home.",
        price_tier="mid",
        product_type="poster",
    ),

    # ── OFFICE MOTIVATION (4 templates) ──
    ListingTemplate(
        niche="Office Motivation Decor",
        title="Leadership Wall Art | Office Motivation Print | Leader Quote Poster Workplace Decor",
        tags=["leadership art", "office motivation", "leader print", "workplace decor",
              "boss wall art", "leader quote", "office decor", "leadership quote",
              "work motivation", "leader decor", "leadership poster", "team leader",
              "office print"],
        description_hook="Great leaders do not just manage teams — they inspire purpose, build trust, and leave every room better than they found it. This leadership motivation print is the statement piece every executive office and conference room deserves.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Office Motivation Decor",
        title="Entrepreneur Wall Art | Business Motivation Print | Hustle Quote Office Decor",
        tags=["entrepreneur art", "business print", "hustle art", "entrepreneur decor",
              "business decor", "startup art", "hustle decor", "founder art",
              "boss art", "grind print", "business poster", "CEO art",
              "entrepreneur print"],
        description_hook="Entrepreneurs do not just build businesses — they build futures on nothing but vision, grit, and the refusal to accept ordinary. This business motivation print belongs in every founder's office, studio, or workspace where big ideas are born.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Office Motivation Decor",
        title="Teamwork Wall Art | Workplace Quote Print | Team Motivation Office Decor Poster",
        tags=["teamwork art", "workplace art", "team motivation", "office teamwork",
              "team print", "team quote", "workplace print", "team decor",
              "office team art", "workplace quote", "team poster", "team art",
              "team work decor"],
        description_hook="Every great achievement starts with a team that trusts each other and shows up fully — this teamwork wall art print is a daily reminder of what happens when people work together toward something bigger than themselves. Office-ready and deeply motivating.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="Office Motivation Decor",
        title="Work Life Balance Print | Wellness Office Art | Mindful Workplace Decor Poster",
        tags=["work life balance", "wellness art", "balance print", "office wellness",
              "mindful work", "balance decor", "work balance", "healthy work",
              "office mindful", "balance poster", "wellness print", "work art",
              "mindful office"],
        description_hook="Balance is not something you find — it is something you build, one intentional decision at a time. This work-life balance office print is a beautifully designed reminder to work hard, rest fully, and live purposefully.",
        price_tier="budget",
        product_type="digital",
    ),

    # ── STATE PRIDE (4 templates) ──
    ListingTemplate(
        niche="State Pride Wall Art",
        title="Georgia State Wall Art | Georgia Print | Georgia Home Decor Georgia Gift Poster",
        tags=["georgia art", "georgia print", "georgia decor", "georgia gift",
              "georgia state", "georgia home", "peach state", "georgia wall art",
              "GA print", "georgia pride", "georgia poster", "south decor",
              "georgia state art"],
        description_hook="Georgia is more than a state — it is sweet tea on the porch, magnolias in bloom, and a Southern warmth that stays with you forever. This Georgia state wall art print is a proud display for anyone who calls the Peach State home.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="State Pride Wall Art",
        title="Florida State Wall Art | Florida Print | Sunshine State Home Decor Florida Gift",
        tags=["florida art", "florida print", "florida decor", "florida gift",
              "florida state", "sunshine state", "florida home", "FL print",
              "florida wall art", "florida pride", "beach state", "florida poster",
              "south florida"],
        description_hook="From the Panhandle to the Keys, Florida is a state of endless sun, salt air, and that unmistakable feeling of freedom. This Florida state wall art print is the perfect gift for anyone whose heart lives somewhere between the Gulf and the Atlantic.",
        price_tier="budget",
        product_type="poster",
    ),
    ListingTemplate(
        niche="State Pride Wall Art",
        title="Texas State Wall Art | Texas Print | Lone Star State Home Decor Texas Gift Art",
        tags=["texas art", "texas print", "texas decor", "texas gift",
              "lone star state", "texas wall art", "texas home", "TX print",
              "texas pride", "texas poster", "big texas", "texas state art",
              "south texas"],
        description_hook="Everything is bigger in Texas — the sky, the pride, and the love for the Lone Star State. This Texas state wall art print is a bold, beautiful tribute for every Texan who wears that title like a badge of honor.",
        price_tier="mid",
        product_type="poster",
    ),
    ListingTemplate(
        niche="State Pride Wall Art",
        title="Tennessee State Wall Art | Tennessee Print | Volunteer State Decor Tennessee Gift",
        tags=["tennessee art", "tennessee print", "tennessee decor", "tennessee gift",
              "volunteer state", "tennessee wall art", "TN print", "nashville art",
              "tennessee home", "TN decor", "tennessee pride", "tennessee poster",
              "country state art"],
        description_hook="Tennessee is where the music flows, the mountains rise, and the roots run deep into red clay and river-rich soil. This Tennessee state wall art print is the perfect gift for anyone who loves the Volunteer State from the Smokies to Music City.",
        price_tier="budget",
        product_type="poster",
    ),
]


def get_templates_by_niche(niche: str) -> list[ListingTemplate]:
    """Templates whose niche contains the given text (case-insensitive)."""
    return [t for t in SEO_TEMPLATES if niche.lower() in t.niche.lower()]


def get_templates_by_price(price_tier: str) -> list[ListingTemplate]:
    """Templates in the given price tier (budget/mid/premium)."""
    return [t for t in SEO_TEMPLATES if t.price_tier == price_tier]


def get_all_niches() -> list[str]:
    """Sorted unique niche names across all templates."""
    return sorted(set(t.niche for t in SEO_TEMPLATES))
